[pypi]
# explicit default url, avoid including local mirror urls
url = "https://pypi.org/simple"

[lock]
format = "pylock"

[install]
# avoid symlinking dependencies in the development venv, see https://github.com/zensical/zensical/issues/786
cache = false
